#!/usr/bin/env python3
"""
Generate .env file from backend/config/config.yml for docker-compose
"""
import yaml
import os
import sys

CONFIG_FILE = "backend/config/config.yml"
ENV_FILE = ".env"

if not os.path.exists(CONFIG_FILE):
    print(f"Error: {CONFIG_FILE} not found")
    sys.exit(1)

try:
    with open(CONFIG_FILE, 'r') as f:
        config = yaml.safe_load(f)
    
    docker_config = config.get('docker', {})
    database_config = config.get('database', {})
    
    # Prefer docker section if exists, otherwise fallback to database section
    if docker_config:
        postgres_user = docker_config.get('postgres_user') or database_config.get('user', 'postgres')
        postgres_password = docker_config.get('postgres_password') or database_config.get('password', '')
        postgres_db = docker_config.get('postgres_db') or database_config.get('dbname', 'lilychat')
    else:
        # Use database section directly
        postgres_user = database_config.get('user', 'postgres')
        postgres_password = database_config.get('password', '')
        postgres_db = database_config.get('dbname', 'lilychat')
    
    if not postgres_password:
        print("Error: postgres_password is empty in config.yml")
        sys.exit(1)
    
    env_content = f"""# Generated from {CONFIG_FILE}
# DO NOT EDIT THIS FILE MANUALLY - edit config.yml and run: python3 scripts/generate-env.py

POSTGRES_USER={postgres_user}
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB={postgres_db}
"""
    
    with open(ENV_FILE, 'w') as f:
        f.write(env_content)
    
    print(f"Generated {ENV_FILE} from {CONFIG_FILE}")
    
except yaml.YAMLError as e:
    print(f"Error parsing YAML: {e}")
    sys.exit(1)
except Exception as e:
    print(f"Error: {e}")
    sys.exit(1)

